# Generated by Django 5.2.8 on 2025-11-18 06:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('one-time', 'One-time'), ('subscription', 'Subscription')], default='one-time', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('active', 'Active'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='in_progress', max_length=20)),
                ('step', models.IntegerField(choices=[(0, 'deposit'), (1, 'design'), (2, 'final'), (3, 'complete')], default=0)),
                ('paid_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.packagecatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.userpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['user'], name='accounts_us_user_id_77f357_idx'),
        ),
        migrations.AddIndex(
            model_name='userpackage',
            index=models.Index(fields=['status'], name='accounts_us_status_27f2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='accounts_pa_user_id_747fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='accounts_pa_status_8957e4_idx'),
        ),
    ]
