# Generated by Django 5.2.8 on 2025-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
