# Generated by Django 5.2.8 on 2025-12-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customeraccount_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
