# Generated by Django 5.2.8 on 2025-11-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Used in the URL.', max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text='Short preview text for cards and SEO.', max_length=350)),
                ('body', models.TextField(help_text='You can paste HTML or plain text.')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('author_name', models.CharField(default='BigSons Team', max_length=120)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx')],
            },
        ),
    ]
