"""
Django settings for bigsons_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# --- tiny env helpers ---
def env_required(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        raise ImproperlyConfigured(f"Missing environment variable: {name}")
    return v

def env(name: str, default=None):
    return os.environ.get(name, default)

# --- environment / mode ---
DJANGO_ENV = env("DJANGO_ENV", "dev").lower()  # dev | prod
DEBUG = DJANGO_ENV != "prod"
IS_PROD = DJANGO_ENV == "prod"

# SECRET_KEY: safe in dev, required from env in prod
SECRET_KEY = env("SECRET_KEY", "dev-unsafe-secret-key") if DEBUG else env_required("SECRET_KEY")
ALLOWED_HOSTS = env("ALLOWED_HOSTS", "127.0.0.1,localhost,[::1]").split(",")
LOGOUT_REDIRECT_URL = "main:home"


# --- Stripe ---
# === Stripe keys ===
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY      = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET  = os.environ.get("STRIPE_WEBHOOK_SECRET", "")  # later for webhooks

# === Monthly Care plan price IDs ===
STRIPE_PRICE_CARE_BASIC = os.environ.get("STRIPE_PRICE_CARE_BASIC", "")  # e.g. price_123
STRIPE_PRICE_CARE_PLUS  = os.environ.get("STRIPE_PRICE_CARE_PLUS", "")
STRIPE_PRICE_CARE_PRO   = os.environ.get("STRIPE_PRICE_CARE_PRO", "")








#Email
EMAIL_SUBJECT_PREFIX = f"[BigSons {DJANGO_ENV.upper()}] "

# Always define these, dev or prod
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    "no-reply <noreply@bigsonsweb.com>",
)
SERVER_EMAIL = env("SERVER_EMAIL", "info@bigsonsweb.com")


if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = env("EMAIL_HOST", "smtp.zoho.com")
    # Prefer TLS 587 with Zoho
    EMAIL_PORT = int(env("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = env("EMAIL_USE_TLS", "True").lower() == "true"
    EMAIL_USE_SSL = env("EMAIL_USE_SSL", "False").lower() == "true"
    EMAIL_TIMEOUT = int(env("EMAIL_TIMEOUT", "15"))

    EMAIL_HOST_USER = env_required("EMAIL_HOST_USER")          # e.g. noreply@bigsonsweb.com
    EMAIL_HOST_PASSWORD = env_required("EMAIL_HOST_PASSWORD")  # Zoho app password (not your login)



# Optional: ADMINS via env (for 500 emails in prod)
def _parse_admins(s: str):
    if not s:
        return []
    out = []
    for part in s.split(","):
        part = part.strip()
        if not part:
            continue
        if "<" in part and ">" in part:
            name, email = part.split("<", 1)
            out.append((name.strip(), email.rstrip(">").strip()))
        else:
            out.append(("", part))
    return out

ADMINS = _parse_admins(env("ADMINS", ""))  # e.g. "Feda <owner@bigsonsweb.com>"
MANAGERS = ADMINS[:]


# Optional: 24-hour token expiry (default is 3 days)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24


# Media (uploads)
MEDIA_URL = "/media/"
STATIC_URL = "/static/"



# Application definition

INSTALLED_APPS = [
    # Your apps first so their templates override admin’s
    'main',
    'accounts',

    # Django contrib apps after
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    'widget_tweaks',
    #blog
    "blog",
    "django.contrib.sitemaps",

    #security
    "csp",
    
]








MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Security/3rd-party
    "csp.middleware.CSPMiddleware",
    
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# WhiteNoise: gzip+brotli and immutable cache for versioned files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'bigsons_site.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],   # <-- this line
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'bigsons_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_POSTGRES = os.environ.get("USE_POSTGRES", "").lower() in {"1", "true", "yes"}

if USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "bigsons_db"),
            "USER": os.environ.get("POSTGRES_USER", "bigsons_user"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Optional: a project-level folder you keep custom static in during dev
STATICFILES_DIRS = [BASE_DIR / "static"]  # safe to leave empty or remove if unused
# For production collectstatic (won’t affect dev)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# who receives contact notifications
CONTACT_NOTIFY_EMAILS = ["bigzadfeda@gmail.com", "fbig@bigsonsweb.com"]
#For local testing, you can temporarily switch to console backend so emails print to the terminal:



# Always keep SecurityMiddleware enabled (you already have it)
# MIDDLEWARE = ["django.middleware.security.SecurityMiddleware", ... ]

# 1) HTTPS & secure cookies
SECURE_SSL_REDIRECT = IS_PROD          # redirect HTTP→HTTPS in prod
SESSION_COOKIE_SECURE = IS_PROD
CSRF_COOKIE_SECURE = IS_PROD

# If behind a proxy/PA, let Django know HTTPS was used (PythonAnywhere sets this)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 2) HSTS (enable only when you’re sure HTTPS works on your domain)
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30 if IS_PROD else 0  # 30 days to start
SECURE_HSTS_INCLUDE_SUBDOMAINS = False       # set True later if you own all subdomains
SECURE_HSTS_PRELOAD = False                  # consider True after monitoring

# 3) CSRF (must include your prod origins)
# env: CSRF_TRUSTED_ORIGINS="https://yourapp.pythonanywhere.com,https://bigsonsweb.com,https://www.bigsonsweb.com"
CSRF_TRUSTED_ORIGINS = (
    os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if IS_PROD else []
)

# 4) X-Content-Type & Referrer Policy
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# 5) Clickjacking
X_FRAME_OPTIONS = "DENY"

# 6) Content Security Policy (basic, tighten as needed)
# Allow your site, inline styles (Bootstrap needs it unless you self-host), and images/data URIs.
# If you load external CDNs, add them explicitly (e.g., https://cdn.jsdelivr.net)
# --- Content Security Policy (django-csp v4) ---
# Report-Only in dev so the console shows what would be blocked without breaking pages.
# In prod we enforce it (and you can add a report-uri if you want reports).
CONTENT_SECURITY_POLICY = {
    "REPORT_ONLY": not IS_PROD,  # dev: report-only; prod: enforce
    "DIRECTIVES": {
        "default-src": ("'self'",),

        # If you use any CDNs for scripts (e.g., jsdelivr), add them here:
        # "script-src": ("'self'", "https://cdn.jsdelivr.net"),
        "script-src": ("'self'",),

        # Bootstrap via inline styles during dev — remove 'unsafe-inline' once you self-host CSS
        "style-src": ("'self'", "'unsafe-inline'"),

        "img-src": ("'self'", "data:"),
        "font-src": ("'self'", "data:"),
        "connect-src": ("'self'",),
        "base-uri": ("'none'",),
        "frame-ancestors": ("'none'",),

        # Only upgrade insecure requests in prod (prevents http assets on https pages)
        **({"upgrade-insecure-requests": True} if IS_PROD else {}),
    },
}




# 8) Logging: email 500s in prod
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {"require_debug_false": {"()": "django.utils.log.RequireDebugFalse"}},
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "django.request": {"handlers": ["mail_admins"], "level": "ERROR", "propagate": True},
        "django.security": {"handlers": ["mail_admins"], "level": "ERROR", "propagate": True},
    },
}


#other security
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # must be False for browser forms to work
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
