# Generated by Django 5.2.8 on 2025-11-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='subject',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='interest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='seo_details',
            field=models.TextField(blank=True),
        ),
    ]
